// Service Worker for ConfigStream
// Uses configuration from cache-config.js

// Import shared configuration
importScripts('assets/js/cache-config.js?v=' + new Date().getTime()); // Bust HTTP cache

// Access config from global scope (set by cache-config.js)
const config = self.ConfigStreamCache || {};
const VERSION = config.VERSION || 'ERR_NO_VERSION'; // Fail loudly if config missing
const CACHE_NAME = config.CACHE_NAME || `configstream-v${VERSION}`;
const ASSETS_TO_CACHE = config.PRECACHE_URLS || [
  'index.html',
  'proxies.html',
  'analytics.html',
  'about.html',
  'wiki.html',
  'assets/css/style.css',
  'assets/js/main.js',
  'assets/js/utils.js'
];

console.log(`[ServiceWorker] Initializing v${VERSION} (${CACHE_NAME})`);

function cacheSuccessfulResponse(request, response) {
  if (!response || !response.ok) {
    return Promise.resolve(false);
  }

  const responseClone = response.clone();
  return caches.open(CACHE_NAME)
    .then(cache => cache.put(request, responseClone))
    .then(() => true);
}

function logBackgroundFetchError(request, error) {
  console.warn('[ServiceWorker] Background fetch failed:', request.url, error);
}

// Install Event: Cache Core Assets
self.addEventListener('install', (event) => {
  self.skipWaiting(); // Force activation
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log(`[ServiceWorker] Pre-caching ${ASSETS_TO_CACHE.length} assets`);
      return cache.addAll(ASSETS_TO_CACHE);
    })
  );
});

// Activate Event: Clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          // Check if cache name starts with prefix but doesn't match current version
          // Cache names generated by cache-config.js always start with
          // "configstream-v" followed by the version string (see CACHE_NAME
          // construction at the top of this file and in cache-config.js).
          if (cacheName.startsWith('configstream-v') && cacheName !== CACHE_NAME) {
            console.log('[ServiceWorker] Removing old cache:', cacheName);
            return caches.delete(cacheName);
          }
        })
      );
    }).then(() => self.clients.claim())
  );
});

// Fetch Event: Network First for Data, Cache First for Assets
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  const strategy = config.CACHE_STRATEGY || {};

  // Helper to check strategy lists
  const matchStrategy = (list) => {
      if (!list) return false;
      return list.some(pattern => url.pathname.endsWith(pattern) || url.href.includes(pattern));
  };

  // Strategy 1: Network First (Fresh Data)
  // Check explicit list or default logic (JSON/API)
  if (matchStrategy(strategy.networkFirst) || url.pathname.endsWith('.json') || url.pathname.includes('/api/')) {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          event.waitUntil(
            cacheSuccessfulResponse(event.request, response)
              .catch(error => logBackgroundFetchError(event.request, error))
          );
          return response;
        })
        .catch(() => {
          // If offline, try cache
          return caches.match(event.request);
        })
    );
    return;
  }

  // Strategy 2: Cache First, Revalidate (Static Assets)
  // Default fallback for everything else
  event.respondWith(
    caches.match(event.request)
      .then((cachedResponse) => {
        if (cachedResponse) {
            // Return cached response immediately
            // Background update (Stale-While-Revalidate)
            if (config.CACHE_CONFIG && config.CACHE_CONFIG.staleWhileRevalidate) {
                event.waitUntil(
                    fetch(event.request)
                        .then(response => cacheSuccessfulResponse(event.request, response))
                        .catch(error => logBackgroundFetchError(event.request, error))
                );
            }
            return cachedResponse;
        }
        // Cache miss -> Network
        return fetch(event.request).then(response => {
             // Cache new static assets
             event.waitUntil(
                 cacheSuccessfulResponse(event.request, response)
                     .catch(error => logBackgroundFetchError(event.request, error))
             );
             return response;
        });
      })
  );
});
