# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate protocol tables from docs/protocol_matrix.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ENCODING = "utf-8"
ROOT = Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "docs" / "protocol_matrix.json"
PROTOCOLS_DOC_PATH = ROOT / "docs" / "wiki" / "project" / "03-protocols.md"
START_MARKER = "<!-- PROTOCOL_MATRIX:START -->"
END_MARKER = "<!-- PROTOCOL_MATRIX:END -->"


def _load_matrix() -> list[dict[str, Any]]:
    data = json.loads(MATRIX_PATH.read_text(encoding=ENCODING))
    protocols = data.get("protocols")
    if not isinstance(protocols, list):
        raise ValueError("docs/protocol_matrix.json must contain a protocols list")
    result: list[dict[str, Any]] = []
    for item in protocols:
        if isinstance(item, dict):
            result.append(item)
    return result


def _display_bool(value: object) -> str:
    return "yes" if value is True else "no"


def _sort_key(item: dict[str, Any]) -> tuple[int, str]:
    kind = item.get("kind", "")
    public = item.get("public", False)
    kind_order = 0 if (public and kind == "canonical") else (1 if public else 2)
    return (kind_order, str(item.get("id", "")))


def render_protocol_table() -> str:
    protocols = sorted(_load_matrix(), key=_sort_key)
    lines = [
        START_MARKER,
        "<!-- Generated by scripts/generate_protocol_docs.py; edit docs/protocol_matrix.json instead. -->",
        "",
        "| Protocol | Kind | Parser Module | Sing-box Export | Clash Export | Notes |",
        "| :--- | :--- | :--- | :--- | :--- | :--- |",
    ]
    for item in protocols:
        proto_id = str(item.get("id", ""))
        kind = str(item.get("kind", ""))
        parser = str(item.get("parser", "") or "N/A")
        singbox = _display_bool(item.get("singbox_export"))
        clash = _display_bool(item.get("clash_export"))
        notes = str(item.get("notes", "")).replace("|", "\\|")
        lines.append(
            f"| **{proto_id}** | {kind} | `{parser}` | {singbox} | {clash} | {notes} |"
        )
    lines.extend(["", END_MARKER])
    return "\n".join(lines)


def _replace_generated_block(path: Path, block: str) -> bool:
    original = path.read_text(encoding=ENCODING)
    start = original.find(START_MARKER)
    end = original.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise ValueError(f"{path} is missing protocol matrix markers")
    end += len(END_MARKER)
    updated = original[:start] + block + original[end:]
    if updated == original:
        return False
    path.write_text(updated, encoding=ENCODING)
    return True


def generate(check: bool = False) -> list[str]:
    block = render_protocol_table()
    errors: list[str] = []
    path = PROTOCOLS_DOC_PATH
    original = path.read_text(encoding=ENCODING)
    try:
        changed = _replace_generated_block(path, block)
    except ValueError as exc:
        errors.append(str(exc))
        return errors
    if check:
        current = path.read_text(encoding=ENCODING)
        path.write_text(original, encoding=ENCODING)
        if changed:
            errors.append(
                f"{path.relative_to(ROOT).as_posix()} protocol table is stale"
            )
        elif current != original:
            errors.append(f"{path.relative_to(ROOT).as_posix()} changed during check")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated protocol tables are stale.",
    )
    args = parser.parse_args()
    errors = generate(check=args.check)
    if errors:
        print("ERROR: protocol docs generation failed")
        for error in errors:
            print(f"  - {error}")
        return 1
    if args.check:
        print("OK: protocol docs are current.")
    else:
        print("OK: protocol docs generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
