# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate user-facing output tables from docs/output_matrix.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ENCODING = "utf-8"
ROOT = Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "docs" / "output_matrix.json"
README_PATH = ROOT / "README.md"
API_REFERENCE_PATH = ROOT / "docs" / "wiki" / "project" / "08-api-reference.md"
START_MARKER = "<!-- OUTPUT_MATRIX:START -->"
END_MARKER = "<!-- OUTPUT_MATRIX:END -->"

CATEGORY_ORDER = {
    "subscription": 0,
    "side-product": 1,
    "control": 2,
    "api": 3,
    "analytics": 4,
    "frontend": 5,
    "docs": 6,
}


def _load_matrix() -> list[dict[str, Any]]:
    data = json.loads(MATRIX_PATH.read_text(encoding=ENCODING))
    outputs = data.get("outputs")
    if not isinstance(outputs, list):
        raise ValueError("docs/output_matrix.json must contain an outputs list")
    result: list[dict[str, Any]] = []
    for item in outputs:
        if isinstance(item, dict):
            result.append(item)
    return result


def _display_bool(value: object) -> str:
    return "yes" if value is True else "no"


def _validation_summary(item: dict[str, Any]) -> str:
    checks: list[str] = []
    if item.get("schema_validation") is True:
        checks.append("schema")
    if item.get("format") in {"json", "jsonl", "yaml", "zip"}:
        checks.append(str(item["format"]))
    if item.get("core_format") in {"sing-box", "clash", "xray"}:
        checks.append("references")
    if item.get("zip_required_members"):
        checks.append("zip members")
    return ", ".join(dict.fromkeys(checks)) or "presence"


def _sort_key(item: dict[str, Any]) -> tuple[int, str, str]:
    category = str(item.get("category", ""))
    family = str(item.get("family", ""))
    path = str(item.get("path", ""))
    return (CATEGORY_ORDER.get(category, 99), family, path)


def render_output_table() -> str:
    outputs = sorted(_load_matrix(), key=_sort_key)
    lines = [
        START_MARKER,
        "<!-- Generated by scripts/generate_output_docs.py; edit docs/output_matrix.json instead. -->",
        "",
        "| Output | Family | Format | Non-empty | Validation | Notes |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in outputs:
        path = str(item.get("path", ""))
        family = str(item.get("family", ""))
        output_format = str(item.get("format", ""))
        nonempty = _display_bool(item.get("nonempty"))
        validation = _validation_summary(item)
        notes = str(item.get("notes", "")).replace("|", "\\|")
        lines.append(
            f"| `{path}` | {family} | {output_format} | {nonempty} | "
            f"{validation} | {notes} |"
        )
    lines.extend(["", END_MARKER])
    return "\n".join(lines)


def _replace_generated_block(path: Path, block: str) -> bool:
    original = path.read_text(encoding=ENCODING)
    start = original.find(START_MARKER)
    end = original.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise ValueError(f"{path} is missing output matrix markers")
    end += len(END_MARKER)
    updated = original[:start] + block + original[end:]
    if updated == original:
        return False
    path.write_text(updated, encoding=ENCODING)
    return True


def generate(check: bool = False) -> list[str]:
    block = render_output_table()
    errors: list[str] = []
    for path in (README_PATH, API_REFERENCE_PATH):
        original = path.read_text(encoding=ENCODING)
        try:
            changed = _replace_generated_block(path, block)
        except ValueError as exc:
            errors.append(str(exc))
            continue
        if check:
            current = path.read_text(encoding=ENCODING)
            path.write_text(original, encoding=ENCODING)
            if changed:
                errors.append(
                    f"{path.relative_to(ROOT).as_posix()} output table is stale"
                )
            elif current != original:
                errors.append(
                    f"{path.relative_to(ROOT).as_posix()} changed during check"
                )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated output tables are stale.",
    )
    args = parser.parse_args()
    errors = generate(check=args.check)
    if errors:
        print("ERROR: output docs generation failed")
        for error in errors:
            print(f"  - {error}")
        return 1
    if args.check:
        print("OK: output docs are current.")
    else:
        print("OK: output docs generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
