# SPDX-License-Identifier: AGPL-3.0-or-later
"""Canonical helpers for loading and rendering release readiness state."""

from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any

ALLOWED_GATE_STATUSES = frozenset(
    {
        "passing",
        "pending",
        "unverified",
        "operator_action_required",
        "failed",
        "skipped",
        "unavailable",
    }
)
ALLOWED_RELEASE_GATES = frozenset(
    {"ready", "external_verification_required", "blocked"}
)
ALLOWED_VERDICTS = frozenset({"PASS", "CONDITIONAL", "FAIL"})


def parse_timestamp(value: str) -> datetime:
    """Parse an ISO-8601 timestamp and require an explicit timezone."""

    if not isinstance(value, str) or not value.strip():
        raise ValueError("timestamp must be a non-empty string")
    normalized = value.strip()
    if normalized.endswith("Z"):
        normalized = f"{normalized[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError as exc:
        raise ValueError(f"invalid ISO-8601 timestamp: {value!r}") from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise ValueError("timestamp must be timezone-aware")
    return parsed.astimezone(timezone.utc)


def load_release_state(path: Path) -> dict[str, Any]:
    """Load a release-state JSON object from *path*."""

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise TypeError("release state must be a JSON object")
    return payload


def _render_evidence(value: object) -> str:
    if not isinstance(value, list) or not value:
        return "-"
    items = [str(item) for item in value if isinstance(item, str) and item]
    if not items:
        return "-"
    return "<br>".join(f"`{item}`" for item in items)


def render_status(state: dict[str, Any]) -> str:
    """Render the human-readable STATUS.md representation deterministically."""

    gates = state.get("required_gates", {})
    gate_rows: list[str] = []
    if isinstance(gates, dict):
        for name in sorted(gates):
            gate = gates[name]
            if not isinstance(gate, dict):
                continue
            status = str(gate.get("status", "unknown"))
            evidence = _render_evidence(gate.get("evidence"))
            gate_rows.append(f"| `{name}` | `{status}` | {evidence} |")

    production_ready = "Yes" if state.get("production_ready") is True else "No"
    lines = [
        "# ConfigStream Project Status",
        "",
        "> Generated from `docs/readiness.json`. Do not edit this file by hand.",
        "",
        f"**Version:** v{state.get('project_version', 'unknown')}",
        f"**Verdict:** {state.get('verdict', 'unknown')}",
        f"**Release gate:** `{state.get('release_gate', 'unknown')}`",
        f"**Production ready:** {production_ready}",
        f"**Evaluated at:** {state.get('evaluated_at', 'unknown')}",
        "",
        "## Required Gates",
        "",
        "| Gate | Status | Evidence |",
        "|---|---|---|",
        *gate_rows,
        "",
        "## Release Invariant",
        "",
        str(state.get("release_invariant", "")),
        "",
        "## Evidence Boundary",
        "",
        str(state.get("evidence_boundary", "")),
        "",
    ]
    return "\n".join(lines)
