# SPDX-License-Identifier: AGPL-3.0-or-later
"""Tests for public output matrix validation."""

from __future__ import annotations

import importlib
import json
import sys
from pathlib import Path

import pytest

from scripts import validate_output_matrix
from scripts.generate_output_docs import generate, render_output_table
from scripts.validate_output_matrix import EXPECTED_ZIP_OPTIONAL_PATTERNS
from scripts.validate_pages_artifact import (
    REQUIRED_EXISTS,
    REQUIRED_NONEMPTY,
    REQUIRED_ZIP_MEMBERS,
)


def _write_json(path: Path, data: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data), encoding="utf-8")


def _minimal_valid_matrix() -> dict[str, object]:
    outputs = []
    for rel_path in REQUIRED_EXISTS:
        family = "test"
        if rel_path.startswith("singbox-vpn"):
            family = "singbox-vpn"
        elif rel_path.startswith("singbox"):
            family = "singbox"
        elif rel_path.startswith("chains"):
            family = "chains"
        elif rel_path.startswith("clash"):
            family = "clash"
        outputs.append(
            {
                "path": rel_path,
                "family": family,
                "category": "control" if rel_path.endswith(".json") else "subscription",
                "format": "json" if rel_path.endswith(".json") else "text",
                "required": True,
                "nonempty": rel_path in REQUIRED_NONEMPTY,
                "schema_validation": rel_path
                in {
                    "artifact_manifest.json",
                    "health.json",
                    "metadata.json",
                    "proxies.json",
                },
                "degraded_valid": True,
                "notes": "test fixture",
                **(
                    {
                        "core_format": (
                            "clash" if rel_path.startswith("clash") else "sing-box"
                        ),
                        "artifact_type": (
                            "full_config_alias"
                            if rel_path.startswith("chains")
                            else "full_config"
                        ),
                    }
                    if rel_path.startswith(("singbox", "chains", "clash"))
                    else {}
                ),
                **(
                    {"zip_required_members": list(REQUIRED_ZIP_MEMBERS[rel_path])}
                    if rel_path in REQUIRED_ZIP_MEMBERS
                    else {}
                ),
                **(
                    {
                        "zip_optional_member_patterns": list(
                            EXPECTED_ZIP_OPTIONAL_PATTERNS[rel_path]
                        )
                    }
                    if rel_path in EXPECTED_ZIP_OPTIONAL_PATTERNS
                    else {}
                ),
            }
        )
    return {"outputs": outputs}


def test_validate_output_matrix_accepts_current_repo() -> None:
    assert validate_output_matrix.validate_output_matrix() == []


def test_output_submodule_import_does_not_eagerly_load_metadata(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delitem(sys.modules, "configstream.output", raising=False)
    monkeypatch.delitem(
        sys.modules, "configstream.output.client_formats", raising=False
    )
    monkeypatch.delitem(sys.modules, "configstream.output.metadata", raising=False)

    importlib.import_module("configstream.output.client_formats")

    assert "configstream.output.metadata" not in sys.modules


def test_generated_output_docs_are_current() -> None:
    assert generate(check=True) == []


def test_generated_output_docs_include_current_required_paths() -> None:
    table = render_output_table()

    for rel_path in REQUIRED_EXISTS:
        assert f"`{rel_path}`" in table
    assert "Generated by scripts/generate_output_docs.py" in table


def test_validate_output_matrix_rejects_missing_required_output(
    tmp_path: Path,
) -> None:
    matrix = _minimal_valid_matrix()
    outputs = matrix["outputs"]
    assert isinstance(outputs, list)
    outputs.pop(0)
    _write_json(tmp_path / "matrix.json", matrix)

    errors = validate_output_matrix.validate_output_matrix(tmp_path / "matrix.json")

    assert any("missing Pages-required outputs" in error for error in errors)


def test_validate_output_matrix_rejects_nonempty_drift(tmp_path: Path) -> None:
    matrix = _minimal_valid_matrix()
    outputs = matrix["outputs"]
    assert isinstance(outputs, list)
    first_nonempty = next(
        item
        for item in outputs
        if isinstance(item, dict) and item["path"] in REQUIRED_NONEMPTY
    )
    first_nonempty["nonempty"] = False
    _write_json(tmp_path / "matrix.json", matrix)

    errors = validate_output_matrix.validate_output_matrix(tmp_path / "matrix.json")

    assert any("nonempty flags drift" in error for error in errors)


def test_validate_output_matrix_rejects_zip_member_drift(tmp_path: Path) -> None:
    matrix = _minimal_valid_matrix()
    outputs = matrix["outputs"]
    assert isinstance(outputs, list)
    side_product = next(
        item
        for item in outputs
        if isinstance(item, dict) and item["path"] == "side_products.zip"
    )
    side_product["zip_required_members"] = ["README.txt"]
    _write_json(tmp_path / "matrix.json", matrix)

    errors = validate_output_matrix.validate_output_matrix(tmp_path / "matrix.json")

    assert any("zip_required_members drift" in error for error in errors)


def test_validate_output_matrix_requires_core_metadata_for_client_configs(
    tmp_path: Path,
) -> None:
    matrix = _minimal_valid_matrix()
    outputs = matrix["outputs"]
    assert isinstance(outputs, list)
    singbox = next(
        item
        for item in outputs
        if isinstance(item, dict) and item["path"] == "singbox.json"
    )
    singbox.pop("core_format")
    _write_json(tmp_path / "matrix.json", matrix)

    errors = validate_output_matrix.validate_output_matrix(tmp_path / "matrix.json")

    assert any("core_format is required" in error for error in errors)


def test_validate_output_matrix_rejects_zip_optional_pattern_drift(
    tmp_path: Path,
) -> None:
    matrix = _minimal_valid_matrix()
    outputs = matrix["outputs"]
    assert isinstance(outputs, list)
    side_product = next(
        item
        for item in outputs
        if isinstance(item, dict) and item["path"] == "side_products.zip"
    )
    side_product["zip_optional_member_patterns"] = ["openvpn/*.conf"]
    _write_json(tmp_path / "matrix.json", matrix)

    errors = validate_output_matrix.validate_output_matrix(tmp_path / "matrix.json")

    assert any("zip_optional_member_patterns drift" in error for error in errors)


def test_validate_output_matrix_rejects_unsafe_zip_optional_pattern(
    tmp_path: Path,
) -> None:
    matrix = _minimal_valid_matrix()
    outputs = matrix["outputs"]
    assert isinstance(outputs, list)
    side_product = next(
        item
        for item in outputs
        if isinstance(item, dict) and item["path"] == "side_products.zip"
    )
    side_product["zip_optional_member_patterns"] = ["../openvpn/*.ovpn"]
    _write_json(tmp_path / "matrix.json", matrix)

    errors = validate_output_matrix.validate_output_matrix(tmp_path / "matrix.json")

    assert any("unsafe pattern" in error for error in errors)
